--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-12-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAMION
--------------------------------------------------------

  CREATE TABLE "APARCANA"."CAMION" 
   (	"MAT_CAR" CHAR(7 BYTE), 
	"MOD_CAR" VARCHAR2(50 BYTE), 
	"TIPO_CAR" VARCHAR2(50 BYTE), 
	"POT_CAR" CHAR(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table CAMIONERO
--------------------------------------------------------

  CREATE TABLE "APARCANA"."CAMIONERO" 
   (	"DNI_CAM" CHAR(8 BYTE), 
	"NOM_CAM" VARCHAR2(50 BYTE), 
	"APE_CAM" VARCHAR2(50 BYTE), 
	"TELEF_CAM" CHAR(9 BYTE), 
	"DIR_CAM" VARCHAR2(100 BYTE), 
	"SAL_CAM" NUMBER(*,0), 
	"POB_CAM" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table CARGO
--------------------------------------------------------

  CREATE TABLE "APARCANA"."CARGO" 
   (	"COD_CARG" CHAR(2 BYTE), 
	"DNI_JEF" CHAR(8 BYTE), 
	"NOM_CARG" VARCHAR2(20 BYTE), 
	"DNI_EMP" CHAR(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "APARCANA"."CLIENTE" 
   (	"DNI_CLIE" CHAR(8 BYTE), 
	"NOM_CLIE" VARCHAR2(50 BYTE), 
	"APE_CLIE" VARCHAR2(50 BYTE), 
	"DIR_CLIE" VARCHAR2(50 BYTE), 
	"TELEF_CLIE" CHAR(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table COMPRA
--------------------------------------------------------

  CREATE TABLE "APARCANA"."COMPRA" 
   (	"DNI_CLIE" CHAR(8 BYTE), 
	"COD_PROD" CHAR(5 BYTE), 
	"FECHA_COM" DATE, 
	"CANT_COM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table CONDUCE
--------------------------------------------------------

  CREATE TABLE "APARCANA"."CONDUCE" 
   (	"MAT_CAR" CHAR(7 BYTE), 
	"DNI_CAM" CHAR(8 BYTE), 
	"FSTART_CON" DATE, 
	"FFINISH_CON" DATE, 
	"PARTIDA_CON" VARCHAR2(30 BYTE), 
	"LLEGADA_CON" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "APARCANA"."EMPLEADO" 
   (	"DNI_EMP" CHAR(8 BYTE), 
	"NOM_EMP" VARCHAR2(50 BYTE), 
	"APE_EMP" VARCHAR2(50 BYTE), 
	"TELEF_EMP" CHAR(9 BYTE), 
	"DIR_EMP" VARCHAR2(100 BYTE), 
	"USER_EMP" VARCHAR2(50 BYTE), 
	"PASS_EMP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table JEFEAREA
--------------------------------------------------------

  CREATE TABLE "APARCANA"."JEFEAREA" 
   (	"DNI_JEF" CHAR(8 BYTE), 
	"NOM_JEF" VARCHAR2(50 BYTE), 
	"APE_JEF" VARCHAR2(50 BYTE), 
	"TELEF_JEF" CHAR(9 BYTE), 
	"DIR_JEF" VARCHAR2(100 BYTE), 
	"USER_JEF" VARCHAR2(50 BYTE), 
	"PASS_JEF" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "APARCANA"."PRODUCTO" 
   (	"COD_PROD" CHAR(5 BYTE), 
	"NOM_PROD" VARCHAR2(50 BYTE), 
	"PREC_PROD" NUMBER(*,0), 
	"DESC_PROD" VARCHAR2(50 BYTE), 
	"COD_PROVI" NUMBER(*,0), 
	"DNI_EMP" CHAR(8 BYTE), 
	"NIF_PROVE" VARCHAR2(20 BYTE), 
	"DNI_CAM" CHAR(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "APARCANA"."PROVEEDOR" 
   (	"NIF_PROVE" VARCHAR2(20 BYTE), 
	"NOM_PROV" VARCHAR2(50 BYTE), 
	"DIR_PROV" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table PROVINCIA
--------------------------------------------------------

  CREATE TABLE "APARCANA"."PROVINCIA" 
   (	"COD_PROVI" NUMBER(*,0), 
	"NOM_PROVI" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
REM INSERTING into APARCANA.CAMION
SET DEFINE OFF;
REM INSERTING into APARCANA.CAMIONERO
SET DEFINE OFF;
REM INSERTING into APARCANA.CARGO
SET DEFINE OFF;
REM INSERTING into APARCANA.CLIENTE
SET DEFINE OFF;
REM INSERTING into APARCANA.COMPRA
SET DEFINE OFF;
REM INSERTING into APARCANA.CONDUCE
SET DEFINE OFF;
REM INSERTING into APARCANA.EMPLEADO
SET DEFINE OFF;
REM INSERTING into APARCANA.JEFEAREA
SET DEFINE OFF;
REM INSERTING into APARCANA.PRODUCTO
SET DEFINE OFF;
REM INSERTING into APARCANA.PROVEEDOR
SET DEFINE OFF;
REM INSERTING into APARCANA.PROVINCIA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index XPKCOMPRA
--------------------------------------------------------

  CREATE UNIQUE INDEX "APARCANA"."XPKCOMPRA" ON "APARCANA"."COMPRA" ("DNI_CLIE", "COD_PROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKEMPLEADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "APARCANA"."XPKEMPLEADO" ON "APARCANA"."EMPLEADO" ("DNI_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKCAMION
--------------------------------------------------------

  CREATE UNIQUE INDEX "APARCANA"."XPKCAMION" ON "APARCANA"."CAMION" ("MAT_CAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKCLIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "APARCANA"."XPKCLIENTE" ON "APARCANA"."CLIENTE" ("DNI_CLIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKJEFEAREA
--------------------------------------------------------

  CREATE UNIQUE INDEX "APARCANA"."XPKJEFEAREA" ON "APARCANA"."JEFEAREA" ("DNI_JEF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKPRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "APARCANA"."XPKPRODUCTO" ON "APARCANA"."PRODUCTO" ("COD_PROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKCONDUCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "APARCANA"."XPKCONDUCE" ON "APARCANA"."CONDUCE" ("MAT_CAR", "DNI_CAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKCARGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "APARCANA"."XPKCARGO" ON "APARCANA"."CARGO" ("COD_CARG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKPROVEEDOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "APARCANA"."XPKPROVEEDOR" ON "APARCANA"."PROVEEDOR" ("NIF_PROVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKCAMIONERO
--------------------------------------------------------

  CREATE UNIQUE INDEX "APARCANA"."XPKCAMIONERO" ON "APARCANA"."CAMIONERO" ("DNI_CAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKPROVINCIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "APARCANA"."XPKPROVINCIA" ON "APARCANA"."PROVINCIA" ("COD_PROVI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  Constraints for Table PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "APARCANA"."PROVEEDOR" ADD CONSTRAINT "XPKPROVEEDOR" PRIMARY KEY ("NIF_PROVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
  ALTER TABLE "APARCANA"."PROVEEDOR" MODIFY ("NIF_PROVE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "APARCANA"."CLIENTE" ADD CONSTRAINT "XPKCLIENTE" PRIMARY KEY ("DNI_CLIE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
  ALTER TABLE "APARCANA"."CLIENTE" MODIFY ("DNI_CLIE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "APARCANA"."EMPLEADO" ADD CONSTRAINT "XPKEMPLEADO" PRIMARY KEY ("DNI_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
  ALTER TABLE "APARCANA"."EMPLEADO" MODIFY ("DNI_EMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAMION
--------------------------------------------------------

  ALTER TABLE "APARCANA"."CAMION" ADD CONSTRAINT "XPKCAMION" PRIMARY KEY ("MAT_CAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
  ALTER TABLE "APARCANA"."CAMION" MODIFY ("MAT_CAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "APARCANA"."PRODUCTO" ADD CONSTRAINT "XPKPRODUCTO" PRIMARY KEY ("COD_PROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
  ALTER TABLE "APARCANA"."PRODUCTO" MODIFY ("DNI_CAM" NOT NULL ENABLE);
  ALTER TABLE "APARCANA"."PRODUCTO" MODIFY ("NIF_PROVE" NOT NULL ENABLE);
  ALTER TABLE "APARCANA"."PRODUCTO" MODIFY ("DNI_EMP" NOT NULL ENABLE);
  ALTER TABLE "APARCANA"."PRODUCTO" MODIFY ("COD_PROVI" NOT NULL ENABLE);
  ALTER TABLE "APARCANA"."PRODUCTO" MODIFY ("COD_PROD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONDUCE
--------------------------------------------------------

  ALTER TABLE "APARCANA"."CONDUCE" ADD CONSTRAINT "XPKCONDUCE" PRIMARY KEY ("MAT_CAR", "DNI_CAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
  ALTER TABLE "APARCANA"."CONDUCE" MODIFY ("DNI_CAM" NOT NULL ENABLE);
  ALTER TABLE "APARCANA"."CONDUCE" MODIFY ("MAT_CAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAMIONERO
--------------------------------------------------------

  ALTER TABLE "APARCANA"."CAMIONERO" ADD CONSTRAINT "XPKCAMIONERO" PRIMARY KEY ("DNI_CAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
  ALTER TABLE "APARCANA"."CAMIONERO" MODIFY ("DNI_CAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROVINCIA
--------------------------------------------------------

  ALTER TABLE "APARCANA"."PROVINCIA" ADD CONSTRAINT "XPKPROVINCIA" PRIMARY KEY ("COD_PROVI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
  ALTER TABLE "APARCANA"."PROVINCIA" MODIFY ("COD_PROVI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CARGO
--------------------------------------------------------

  ALTER TABLE "APARCANA"."CARGO" ADD CONSTRAINT "XPKCARGO" PRIMARY KEY ("COD_CARG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
  ALTER TABLE "APARCANA"."CARGO" MODIFY ("DNI_EMP" NOT NULL ENABLE);
  ALTER TABLE "APARCANA"."CARGO" MODIFY ("DNI_JEF" NOT NULL ENABLE);
  ALTER TABLE "APARCANA"."CARGO" MODIFY ("COD_CARG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPRA
--------------------------------------------------------

  ALTER TABLE "APARCANA"."COMPRA" ADD CONSTRAINT "XPKCOMPRA" PRIMARY KEY ("DNI_CLIE", "COD_PROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
  ALTER TABLE "APARCANA"."COMPRA" MODIFY ("CANT_COM" NOT NULL ENABLE);
  ALTER TABLE "APARCANA"."COMPRA" MODIFY ("FECHA_COM" NOT NULL ENABLE);
  ALTER TABLE "APARCANA"."COMPRA" MODIFY ("COD_PROD" NOT NULL ENABLE);
  ALTER TABLE "APARCANA"."COMPRA" MODIFY ("DNI_CLIE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JEFEAREA
--------------------------------------------------------

  ALTER TABLE "APARCANA"."JEFEAREA" ADD CONSTRAINT "XPKJEFEAREA" PRIMARY KEY ("DNI_JEF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
  ALTER TABLE "APARCANA"."JEFEAREA" MODIFY ("DNI_JEF" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CARGO
--------------------------------------------------------

  ALTER TABLE "APARCANA"."CARGO" ADD CONSTRAINT "R/1" FOREIGN KEY ("DNI_JEF")
	  REFERENCES "APARCANA"."JEFEAREA" ("DNI_JEF") ENABLE;
  ALTER TABLE "APARCANA"."CARGO" ADD CONSTRAINT "R/2" FOREIGN KEY ("DNI_EMP")
	  REFERENCES "APARCANA"."EMPLEADO" ("DNI_EMP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPRA
--------------------------------------------------------

  ALTER TABLE "APARCANA"."COMPRA" ADD CONSTRAINT "R/3" FOREIGN KEY ("DNI_CLIE")
	  REFERENCES "APARCANA"."CLIENTE" ("DNI_CLIE") ENABLE;
  ALTER TABLE "APARCANA"."COMPRA" ADD CONSTRAINT "R/5" FOREIGN KEY ("COD_PROD")
	  REFERENCES "APARCANA"."PRODUCTO" ("COD_PROD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONDUCE
--------------------------------------------------------

  ALTER TABLE "APARCANA"."CONDUCE" ADD CONSTRAINT "R/6" FOREIGN KEY ("MAT_CAR")
	  REFERENCES "APARCANA"."CAMION" ("MAT_CAR") ENABLE;
  ALTER TABLE "APARCANA"."CONDUCE" ADD CONSTRAINT "R/8" FOREIGN KEY ("DNI_CAM")
	  REFERENCES "APARCANA"."CAMIONERO" ("DNI_CAM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "APARCANA"."PRODUCTO" ADD CONSTRAINT "R/10" FOREIGN KEY ("DNI_EMP")
	  REFERENCES "APARCANA"."EMPLEADO" ("DNI_EMP") ENABLE;
  ALTER TABLE "APARCANA"."PRODUCTO" ADD CONSTRAINT "R/11" FOREIGN KEY ("NIF_PROVE")
	  REFERENCES "APARCANA"."PROVEEDOR" ("NIF_PROVE") ENABLE;
  ALTER TABLE "APARCANA"."PRODUCTO" ADD CONSTRAINT "R/12" FOREIGN KEY ("DNI_CAM")
	  REFERENCES "APARCANA"."CAMIONERO" ("DNI_CAM") ENABLE;
  ALTER TABLE "APARCANA"."PRODUCTO" ADD CONSTRAINT "R/9" FOREIGN KEY ("COD_PROVI")
	  REFERENCES "APARCANA"."PROVINCIA" ("COD_PROVI") ENABLE;
