--------------------------------------------------------
-- Archivo creado  - jueves-diciembre-06-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAMION_BAK
--------------------------------------------------------

  CREATE TABLE "VENTOCILLA"."CAMION_BAK" 
   (	"MAT_CAR" CHAR(7 BYTE), 
	"MOD_CAR" VARCHAR2(50 BYTE), 
	"TIPO_CAR" VARCHAR2(50 BYTE), 
	"POT_CAR" CHAR(5 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table CAMIONERO_BAK
--------------------------------------------------------

  CREATE TABLE "VENTOCILLA"."CAMIONERO_BAK" 
   (	"DNI_CAM" CHAR(8 BYTE), 
	"NOM_CAM" VARCHAR2(50 BYTE), 
	"APE_CAM" VARCHAR2(50 BYTE), 
	"TELEF_CAM" CHAR(9 BYTE), 
	"DIR_CAM" VARCHAR2(100 BYTE), 
	"SAL_CAM" NUMBER(*,0), 
	"POB_CAM" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table CARGO_BAK
--------------------------------------------------------

  CREATE TABLE "VENTOCILLA"."CARGO_BAK" 
   (	"COD_CARG" CHAR(2 BYTE), 
	"DNI_JEF" CHAR(8 BYTE), 
	"NOM_CARG" VARCHAR2(20 BYTE), 
	"DNI_EMP" CHAR(8 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table CLIENTE_BAK
--------------------------------------------------------

  CREATE TABLE "VENTOCILLA"."CLIENTE_BAK" 
   (	"DNI_CLIE" CHAR(8 BYTE), 
	"NOM_CLIE" VARCHAR2(50 BYTE), 
	"APE_CLIE" VARCHAR2(50 BYTE), 
	"DIR_CLIE" VARCHAR2(50 BYTE), 
	"TELEF_CLIE" CHAR(9 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table COMPRA_BAK
--------------------------------------------------------

  CREATE TABLE "VENTOCILLA"."COMPRA_BAK" 
   (	"DNI_CLIE" CHAR(8 BYTE), 
	"COD_PROD" CHAR(5 BYTE), 
	"FECHA_COM" DATE, 
	"CANT_COM" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table CONDUCE_BAK
--------------------------------------------------------

  CREATE TABLE "VENTOCILLA"."CONDUCE_BAK" 
   (	"MAT_CAR" CHAR(7 BYTE), 
	"DNI_CAM" CHAR(8 BYTE), 
	"FSTART_CON" DATE, 
	"FFINISH_CON" DATE, 
	"PARTIDA_CON" VARCHAR2(30 BYTE), 
	"LLEGADA_CON" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO_BAK
--------------------------------------------------------

  CREATE TABLE "VENTOCILLA"."EMPLEADO_BAK" 
   (	"DNI_EMP" CHAR(8 BYTE), 
	"NOM_EMP" VARCHAR2(50 BYTE), 
	"APE_EMP" VARCHAR2(50 BYTE), 
	"TELEF_EMP" CHAR(9 BYTE), 
	"DIR_EMP" VARCHAR2(100 BYTE), 
	"USER_EMP" VARCHAR2(50 BYTE), 
	"PASS_EMP" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table JEFEAREA_BAK
--------------------------------------------------------

  CREATE TABLE "VENTOCILLA"."JEFEAREA_BAK" 
   (	"DNI_JEF" CHAR(8 BYTE), 
	"NOM_JEF" VARCHAR2(50 BYTE), 
	"APE_JEF" VARCHAR2(50 BYTE), 
	"TELEF_JEF" CHAR(9 BYTE), 
	"DIR_JEF" VARCHAR2(100 BYTE), 
	"USER_JEF" VARCHAR2(50 BYTE), 
	"PASS_JEF" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO_BAK
--------------------------------------------------------

  CREATE TABLE "VENTOCILLA"."PRODUCTO_BAK" 
   (	"COD_PROD" CHAR(5 BYTE), 
	"NOM_PROD" VARCHAR2(50 BYTE), 
	"PREC_PROD" NUMBER(*,0), 
	"DESC_PROD" VARCHAR2(50 BYTE), 
	"COD_PROVI" NUMBER(*,0), 
	"DNI_EMP" CHAR(8 BYTE), 
	"NIF_PROVE" VARCHAR2(20 BYTE), 
	"DNI_CAM" CHAR(8 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table PROVEEDOR_BAK
--------------------------------------------------------

  CREATE TABLE "VENTOCILLA"."PROVEEDOR_BAK" 
   (	"NIF_PROVE" VARCHAR2(20 BYTE), 
	"NOM_PROV" VARCHAR2(50 BYTE), 
	"DIR_PROV" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Table PROVINCIA_BAK
--------------------------------------------------------

  CREATE TABLE "VENTOCILLA"."PROVINCIA_BAK" 
   (	"COD_PROVI" NUMBER(*,0), 
	"NOM_PROVI" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
REM INSERTING into VENTOCILLA.CAMION_BAK
SET DEFINE OFF;
REM INSERTING into VENTOCILLA.CAMIONERO_BAK
SET DEFINE OFF;
REM INSERTING into VENTOCILLA.CARGO_BAK
SET DEFINE OFF;
REM INSERTING into VENTOCILLA.CLIENTE_BAK
SET DEFINE OFF;
REM INSERTING into VENTOCILLA.COMPRA_BAK
SET DEFINE OFF;
REM INSERTING into VENTOCILLA.CONDUCE_BAK
SET DEFINE OFF;
REM INSERTING into VENTOCILLA.EMPLEADO_BAK
SET DEFINE OFF;
REM INSERTING into VENTOCILLA.JEFEAREA_BAK
SET DEFINE OFF;
REM INSERTING into VENTOCILLA.PRODUCTO_BAK
SET DEFINE OFF;
REM INSERTING into VENTOCILLA.PROVEEDOR_BAK
SET DEFINE OFF;
REM INSERTING into VENTOCILLA.PROVINCIA_BAK
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index XPKPROVINCIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENTOCILLA"."XPKPROVINCIA" ON "VENTOCILLA"."PROVINCIA_BAK" ("COD_PROVI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKPRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENTOCILLA"."XPKPRODUCTO" ON "VENTOCILLA"."PRODUCTO_BAK" ("COD_PROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKCONDUCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENTOCILLA"."XPKCONDUCE" ON "VENTOCILLA"."CONDUCE_BAK" ("MAT_CAR", "DNI_CAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKEMPLEADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENTOCILLA"."XPKEMPLEADO" ON "VENTOCILLA"."EMPLEADO_BAK" ("DNI_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKCOMPRA
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENTOCILLA"."XPKCOMPRA" ON "VENTOCILLA"."COMPRA_BAK" ("DNI_CLIE", "COD_PROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKPROVEEDOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENTOCILLA"."XPKPROVEEDOR" ON "VENTOCILLA"."PROVEEDOR_BAK" ("NIF_PROVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKCAMION
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENTOCILLA"."XPKCAMION" ON "VENTOCILLA"."CAMION_BAK" ("MAT_CAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKCLIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENTOCILLA"."XPKCLIENTE" ON "VENTOCILLA"."CLIENTE_BAK" ("DNI_CLIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKCARGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENTOCILLA"."XPKCARGO" ON "VENTOCILLA"."CARGO_BAK" ("COD_CARG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKJEFEAREA
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENTOCILLA"."XPKJEFEAREA" ON "VENTOCILLA"."JEFEAREA_BAK" ("DNI_JEF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Index XPKCAMIONERO
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENTOCILLA"."XPKCAMIONERO" ON "VENTOCILLA"."CAMIONERO_BAK" ("DNI_CAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL" ;
--------------------------------------------------------
--  DDL for Synonymn CAMIONERO_SIN
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "VENTOCILLA"."CAMIONERO_SIN" FOR "VENTOCILLA"."CAMIONERO_BAK";
--------------------------------------------------------
--  DDL for Synonymn CAMION_SIN
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "VENTOCILLA"."CAMION_SIN" FOR "VENTOCILLA"."CAMION_BAK";
--------------------------------------------------------
--  DDL for Synonymn CARGO_SIN
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "VENTOCILLA"."CARGO_SIN" FOR "VENTOCILLA"."CARGO_BAK";
--------------------------------------------------------
--  DDL for Synonymn CLIENTE_SIN
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "VENTOCILLA"."CLIENTE_SIN" FOR "VENTOCILLA"."CLIENTE_BAK";
--------------------------------------------------------
--  DDL for Synonymn COMPRA_SIN
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "VENTOCILLA"."COMPRA_SIN" FOR "VENTOCILLA"."COMPRA_BAK";
--------------------------------------------------------
--  DDL for Synonymn CONDUCE_SIN
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "VENTOCILLA"."CONDUCE_SIN" FOR "VENTOCILLA"."CONDUCE_BAK";
--------------------------------------------------------
--  DDL for Synonymn EMPLEADO_SIN
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "VENTOCILLA"."EMPLEADO_SIN" FOR "VENTOCILLA"."EMPLEADO_BAK";
--------------------------------------------------------
--  DDL for Synonymn JEFEAREA_SIN
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "VENTOCILLA"."JEFEAREA_SIN" FOR "VENTOCILLA"."JEFEAREA_BAK";
--------------------------------------------------------
--  DDL for Synonymn PRODUCTO_SIN
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "VENTOCILLA"."PRODUCTO_SIN" FOR "VENTOCILLA"."PRODUCTO_BAK";
--------------------------------------------------------
--  DDL for Synonymn PROVEEDOR_SIN
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "VENTOCILLA"."PROVEEDOR_SIN" FOR "VENTOCILLA"."PROVEEDOR_BAK";
--------------------------------------------------------
--  DDL for Synonymn PROVINCIA_SIN
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "VENTOCILLA"."PROVINCIA_SIN" FOR "VENTOCILLA"."PROVINCIA_BAK";
--------------------------------------------------------
--  Constraints for Table PROVINCIA_BAK
--------------------------------------------------------

  ALTER TABLE "VENTOCILLA"."PROVINCIA_BAK" MODIFY ("COD_PROVI" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."PROVINCIA_BAK" ADD CONSTRAINT "XPKPROVINCIA" PRIMARY KEY ("COD_PROVI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONDUCE_BAK
--------------------------------------------------------

  ALTER TABLE "VENTOCILLA"."CONDUCE_BAK" MODIFY ("MAT_CAR" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."CONDUCE_BAK" MODIFY ("DNI_CAM" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."CONDUCE_BAK" ADD CONSTRAINT "XPKCONDUCE" PRIMARY KEY ("MAT_CAR", "DNI_CAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JEFEAREA_BAK
--------------------------------------------------------

  ALTER TABLE "VENTOCILLA"."JEFEAREA_BAK" MODIFY ("DNI_JEF" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."JEFEAREA_BAK" ADD CONSTRAINT "XPKJEFEAREA" PRIMARY KEY ("DNI_JEF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPRA_BAK
--------------------------------------------------------

  ALTER TABLE "VENTOCILLA"."COMPRA_BAK" MODIFY ("DNI_CLIE" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."COMPRA_BAK" MODIFY ("COD_PROD" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."COMPRA_BAK" MODIFY ("FECHA_COM" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."COMPRA_BAK" MODIFY ("CANT_COM" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."COMPRA_BAK" ADD CONSTRAINT "XPKCOMPRA" PRIMARY KEY ("DNI_CLIE", "COD_PROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CARGO_BAK
--------------------------------------------------------

  ALTER TABLE "VENTOCILLA"."CARGO_BAK" MODIFY ("COD_CARG" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."CARGO_BAK" MODIFY ("DNI_JEF" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."CARGO_BAK" MODIFY ("DNI_EMP" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."CARGO_BAK" ADD CONSTRAINT "XPKCARGO" PRIMARY KEY ("COD_CARG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE_BAK
--------------------------------------------------------

  ALTER TABLE "VENTOCILLA"."CLIENTE_BAK" MODIFY ("DNI_CLIE" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."CLIENTE_BAK" ADD CONSTRAINT "XPKCLIENTE" PRIMARY KEY ("DNI_CLIE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CAMION_BAK
--------------------------------------------------------

  ALTER TABLE "VENTOCILLA"."CAMION_BAK" MODIFY ("MAT_CAR" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."CAMION_BAK" ADD CONSTRAINT "XPKCAMION" PRIMARY KEY ("MAT_CAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLEADO_BAK
--------------------------------------------------------

  ALTER TABLE "VENTOCILLA"."EMPLEADO_BAK" MODIFY ("DNI_EMP" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."EMPLEADO_BAK" ADD CONSTRAINT "XPKEMPLEADO" PRIMARY KEY ("DNI_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CAMIONERO_BAK
--------------------------------------------------------

  ALTER TABLE "VENTOCILLA"."CAMIONERO_BAK" MODIFY ("DNI_CAM" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."CAMIONERO_BAK" ADD CONSTRAINT "XPKCAMIONERO" PRIMARY KEY ("DNI_CAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVEEDOR_BAK
--------------------------------------------------------

  ALTER TABLE "VENTOCILLA"."PROVEEDOR_BAK" MODIFY ("NIF_PROVE" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."PROVEEDOR_BAK" ADD CONSTRAINT "XPKPROVEEDOR" PRIMARY KEY ("NIF_PROVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO_BAK
--------------------------------------------------------

  ALTER TABLE "VENTOCILLA"."PRODUCTO_BAK" MODIFY ("COD_PROD" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."PRODUCTO_BAK" MODIFY ("COD_PROVI" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."PRODUCTO_BAK" MODIFY ("DNI_EMP" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."PRODUCTO_BAK" MODIFY ("NIF_PROVE" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."PRODUCTO_BAK" MODIFY ("DNI_CAM" NOT NULL ENABLE);
 
  ALTER TABLE "VENTOCILLA"."PRODUCTO_BAK" ADD CONSTRAINT "XPKPRODUCTO" PRIMARY KEY ("COD_PROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "EMPRESATEXTIL"  ENABLE;
