package GUI.Consultas;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import Bean.UsuarioBean;
import DAO.UsuarioDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
    

public class FrmModificarUsuario extends javax.swing.JFrame {

UsuarioBean usubean = new UsuarioBean();
UsuarioDAO usuariodao= new UsuarioDAO();
String usu=usubean.getUsusave();
String pass=usubean.getPasssave();
    public FrmModificarUsuario() {
        initComponents();
        
        System.out.println("USU:"+usu+"PASS:"+pass);
        this.jcbuser.setModel(usuariodao.Obt_date(usu,pass,"USERNAME"));
        this.jcbusers.setModel(usuariodao.Obt_date(usu,pass,"USERNAME"));
        this.jcbtablespace.setModel(usuariodao.Obt_date(usu,pass,"DEFAULT_TABLESPACE"));
        this.jcbtemporary.setModel(usuariodao.Obt_date(usu,pass,"TEMPORARY_TABLESPACE"));
        
        
        mostrar_privi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newpass = new javax.swing.JTextField();
        newquota = new javax.swing.JTextField();
        btnmodificar = new javax.swing.JButton();
        jcbtablespace = new javax.swing.JComboBox<>();
        jcbtemporary = new javax.swing.JComboBox<>();
        jcbuser = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableprivi = new javax.swing.JTable();
        btnactualizarprivi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbtipo = new javax.swing.JComboBox<>();
        jcbusers = new javax.swing.JComboBox<>();
        jcbprivi = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnanadirprivi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Usuario :");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña :");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Tablespace :");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Temporary Tablespace :");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Quota Temporary Tablespace :");

        newpass.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        newquota.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        btnmodificar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnmodificar.setText("MODIFICAR USUARIO");
        btnmodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmodificarMouseClicked(evt);
            }
        });
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        jcbtablespace.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jcbtablespace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbtemporary.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jcbtemporary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbuser.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jcbuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newpass, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(newquota, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbtablespace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbtemporary, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbuser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbtablespace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbtemporary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newquota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(45, 45, 45)
                .addComponent(btnmodificar)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("USUARIO", jPanel1);

        jtableprivi.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jtableprivi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtableprivi);

        btnactualizarprivi.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnactualizarprivi.setText("ACTUALIZAR PRIVILEGIOS DE USUARIO");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("Seleccionar usuario :");

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setText("Privilegio :");

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setText("Tipo :");

        jcbtipo.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jcbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[SELECCIONAR]", "CLUSTERS", "DATABASE", "DATABASE LINKS", "DIMENSIONS", "INDEXES", "PROCEDURES", "PROFILES", "ROLES", "ROLLBACK SEGMENTS", "SEQUENCES", "SESSIONS", "SYNONYMS", "TABLES", "TABLESPACES", "TRIGGERS", "USERS", "VIEWS" }));
        jcbtipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbtipoItemStateChanged(evt);
            }
        });

        jcbusers.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jcbusers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbprivi.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jcbprivi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[SELECCIONAR]" }));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setText("A continuación se podrá agregar privilegios al usuario seleccionado");

        btnanadirprivi.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        btnanadirprivi.setText("AÑADIR PRIVILEGIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(btnactualizarprivi)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnanadirprivi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbprivi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jcbusers, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcbusers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbprivi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(35, 35, 35)
                        .addComponent(btnanadirprivi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnactualizarprivi)
                .addGap(39, 39, 39))
        );

        jTabbedPane5.addTab("PRIVILEGIOS", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("TABLAS", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbtipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbtipoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.jcbtipo.getSelectedIndex()>=0) {
                this.jcbprivi.setModel(new DefaultComboBoxModel(this.getPrivilegio(this.jcbtipo.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_jcbtipoItemStateChanged

    private void btnmodificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodificarMouseClicked
        // TODO add your handling code here:
        UsuarioDAO p=new UsuarioDAO();
        String usu = (String)jcbuser.getSelectedItem();
        String pass= newpass.getText();
       // String tablespace = (String)jcbtablespace.getSelectedItem();
        String tablespace="USERS";
        String temptablespace="TEMP";
        //String temptablespace = (String)jcbtemporary.getSelectedItem();
        int quota=Integer.parseInt(newquota.getText());
        p.modificar(usu, pass, tablespace, temptablespace, quota);
    }//GEN-LAST:event_btnmodificarMouseClicked

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificarActionPerformed

    //Creacion  de los combobox fluidos
    public String[] getPrivilegio(String tipo){
        
        String[] privi = new String[11];
        
        //TIPO 0
        if (tipo.equalsIgnoreCase("[SELECCIONAR]")){
            privi[0] = "[SELECCIONAR]";
        }
        
        //TIPO 1
        if (tipo.equalsIgnoreCase("CLUSTERS")) {
            privi[0] = "CREATE CLUSTER";
            privi[1] = "CREATE ANY CLUSTER";
            privi[2] = "ALTER ANY CLUSTER";
            privi[3] = "DROP ANY CLUSTER";
        }
        
        //TIPO 2
        if (tipo.equalsIgnoreCase("DATABASE")) {
            privi[0] = "ALTER DATABASE";
            privi[1] = "ALTER SYSTEM";
            privi[2] = "AUDIT SYSTEM";
        }
        
        //TIPO 3
        if (tipo.equalsIgnoreCase("DATABASE LINKS")) {
            privi[0] = "CREATE DATABASE LINK";
            privi[1] = "CREATE PUBLIC DATABASE LINK";
            privi[2] = "DROP PUBLIC DATABASE LINK";
        }
        
        //TIPO 4
        if (tipo.equalsIgnoreCase("DIMENSIONS")) {
            privi[0] = "CREATE DIMENSION";
            privi[1] = "CREATE ANY DIMENSION";
            privi[2] = "ALTER ANY DIMENSION";
            privi[3] = "DROP ANY DIMENSION";
        }
        
        //TIPO 5
        if (tipo.equalsIgnoreCase("INDEXES")) {
            privi[0] = "CREATE ANY INDEX";
            privi[1] = "ALTER ANY INDEX";
            privi[2] = "DROP ANY INDEX";
            privi[3] = "GLOBAL QUERY REWRITE";
        }
        
        //TIPO 6
        if (tipo.equalsIgnoreCase("PROCEDURES")) {
            privi[0] = "CREATE PROCEDURE";
            privi[1] = "CREATE ANY PROCEDURE";
            privi[2] = "ALTER ANY PROCEDURE";
            privi[3] = "DROP ANY PROCEDURE";
            privi[4] = "EXECUTE ANY PROCEDURE";
        }
        
        //TIPO 7
        if (tipo.equalsIgnoreCase("PROFILES")) {
            privi[0] = "CREATE PROFILE";
            privi[1] = "ALTER PROFILE";
            privi[2] = "DROP PROFILE";
        }
        
        //TIPO 8
        if (tipo.equalsIgnoreCase("ROLES")) {
            privi[0] = "CREATE ROLE";
            privi[1] = "ALTER ANY ROLE";
            privi[2] = "DROP ANY ROLE";
            privi[3] = "GRANT ANY ROLE";
        }
        
        //TIPO 9
        if (tipo.equalsIgnoreCase("ROLLBACK SEGMENTS")) {
            privi[0] = "CREATE ROLLBACK SEGMENT";
            privi[1] = "ALTER ROLLBACK SEGMENT";
            privi[2] = "DROP ROLLBACK SEGMENT";
        }
        
        //TIPO 10
        if (tipo.equalsIgnoreCase("SEQUENCES")) {
            privi[0] = "CREATE SEQUENCE";
            privi[1] = "CREATE ANY SEQUENCE";
            privi[2] = "ALTER ANY SEQUENCE";
            privi[3] = "DROP ANY SEQUENCE";
            privi[4] = "SELECT ANY SEQUENCE";
        }
        
        //TIPO 11
        if (tipo.equalsIgnoreCase("SESSIONS")) {
            privi[0] = "CREATE SESSION";
            privi[1] = "ALTER RESOURCE COST";
            privi[2] = "ALTER SESSION";
            privi[3] = "RESTRICTED SESSION";
        }
        
        //TIPO 12
        if (tipo.equalsIgnoreCase("SYNONYMS")) {
            privi[0] = "CREATE SYNONYM";
            privi[1] = "CREATE ANY SYNONYM";
            privi[2] = "CREATE PUBLIC SYNONYM";
            privi[3] = "DROP ANY SYNONYM";
            privi[4] = "DROP PUBLIC SYNONYM";
        }
        
        //TIPO 13
        if (tipo.equalsIgnoreCase("TABLES")) {
            privi[0] = "CREATE TABLE";
            privi[1] = "CREATE ANY TABLE";
            privi[2] = "ALTER ANY TABLE";
            privi[3] = "BACKUP ANY TABLE";
            privi[4] = "DELETE ANY TABLE";
            privi[5] = "DROP ANY TABLE";
            privi[6] = "INSERT ANY TABLE";
            privi[7] = "LOCK ANY TABLE";
            privi[8] = "SELECT ANY TABLE";
            privi[9] = "FLASHBACK ANY TABLE";
            privi[10] = "UPDATE ANY TABLE";
        }
        
        //TIPO 14
        if (tipo.equalsIgnoreCase("TABLESPACES")) {
            privi[0] = "CREATE TABLESPACE";
            privi[1] = "ALTER TABLESPACE";
            privi[2] = "DROP TABLESPACE";
            privi[3] = "MANAGE TABLESPACE";
            privi[4] = "UNLIMITED TABLESPACE";
        }
        
        //TIPO 15
        if (tipo.equalsIgnoreCase("TRIGGERS")) {
            privi[0] = "CREATE TRIGGER";
            privi[1] = "CREATE ANY TRIGGER";
            privi[2] = "ALTER ANY TRIGGER";
            privi[3] = "DROP ANY TRIGGER";
            privi[4] = "ADMINISTER DATABASE TRIGGER";
        }
        
        //TIPO 16
        if (tipo.equalsIgnoreCase("USERS")) {
            privi[0] = "CREATE USER";
            privi[1] = "ALTER USER";
            privi[2] = "BECOME USER";
            privi[3] = "DROP USER";
        }
        
        //TIPO 17
        if (tipo.equalsIgnoreCase("VIEWS")) {
            privi[0] = "CREATE VIEW";
            privi[1] = "CREATE ANY VIEW";
            privi[2] = "DROP ANY VIEW";
        }
        
        return privi;
    }
    
    public void mostrar_privi(){
        ResultSet priv;
        DefaultTableModel privi = (DefaultTableModel) jtableprivi.getModel();
        privi.setRowCount(0);
        priv = Conexiones.ConexionBD.Consulta(usu,pass,"select * from session_privs");
        try {
            while (priv.next()) {                
                Vector p = new Vector();
                p.add(priv.getString(1));
                privi.addRow(p);
                jtableprivi.setModel(privi);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModificarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizarprivi;
    private javax.swing.JButton btnanadirprivi;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JComboBox<String> jcbprivi;
    private javax.swing.JComboBox<String> jcbtablespace;
    private javax.swing.JComboBox<String> jcbtemporary;
    private javax.swing.JComboBox<String> jcbtipo;
    private javax.swing.JComboBox<String> jcbuser;
    private javax.swing.JComboBox<String> jcbusers;
    private javax.swing.JTable jtableprivi;
    private javax.swing.JTextField newpass;
    private javax.swing.JTextField newquota;
    // End of variables declaration//GEN-END:variables
}
